export const commune = {
  nom: "Villeneuve-sur-Loire",
  service: "Service des sports",
  objectif_ratio: 0.30,
};

export const kpis = {
  clubs_actifs: 14,
  clubs_total: 17,
  invitations_en_attente: 3,
  subventions_versees: 122000,
  sponsoring_leve: 28150,
  total_financement: 150150,
  ratio_ss: 0.23,
  delta_sponsoring: "+38 %",
};

export const subventions_detail = [
  { source: "Municipale", montant: 82000 },
  { source: "Conseil départemental", montant: 22000 },
  { source: "Région", montant: 12000 },
  { source: "ANS / fédération", montant: 6000 },
];

export const clubs = [
  {
    id: "1",
    sigle: "FC",
    nom: "FC Villeneuve",
    president: "J. Marchand",
    discipline: "Football",
    licencies: 312,
    subventions: 30000,
    sponsoring: 12050,
    ratio: 0.40,
    dynamisme: "+38 %",
    statut: "actif",
    dynamisme_chip: "ok",
    interet_general: true,
    description: "Un club de quartier avec deux équipes seniors, une école de foot pour les 6-12 ans et une section féminine relancée en 2024.",
    equipes: 5,
    encadrants: 14,
    fonde: "1972",
    packs: [
      { niveau: "Bronze", titre: "Pack Supporter", prix: 100, periodicite: "an", contreparties: ["Logo sur le site du club", "Mention au gala de fin de saison"], places: null, vendus: 3, chip: "outline" },
      { niveau: "Argent", titre: "Pack Partenaire", prix: 500, periodicite: "an", contreparties: ["Bannière permanente au gymnase", "Post réseaux sociaux mensuel"], places: 10, vendus: 4, chip: "outline" },
      { niveau: "Or", titre: "Pack Maillot", prix: 1500, periodicite: "an", contreparties: ["Logo sur le maillot de l'équipe première", "Bannière + post mensuel + invitation gala VIP"], places: 3, vendus: 2, chip: "amber", feature: true },
    ],
    sponsors: [
      { sigle: "GC", nom: "Garage du Centre", contact: "Camille R.", pack: "Or maillot", pack_chip: "amber", montant: 1500, debut: "14 juin 2025", echeance: "12 juin 2026", jours_restants: 22, statut: "warn", statut_label: "à renouveler" },
      { sigle: "PM", nom: "Pizz'à Mario", contact: "M. Riccardi", pack: "Argent", pack_chip: "outline", montant: 500, debut: "28 juin 2025", echeance: "28 juin 2026", jours_restants: 36, statut: "warn", statut_label: "à renouveler" },
      { sigle: "BP", nom: "Boulangerie Paul & Fils", contact: "don récurrent", pack: "Don 25 €/mois", pack_chip: "outline", montant: 300, debut: "—", echeance: "—", jours_restants: null, statut: "ok", statut_label: "payé · récurrent" },
      { sigle: "MC", nom: "Cabinet Médi-Centre", contact: "Dr B. Larrieu", pack: "Bronze", pack_chip: "outline", montant: 100, debut: "15 sept 2025", echeance: "15 sept 2026", jours_restants: null, statut: "ok", statut_label: "payé" },
      { sigle: "AD", nom: "Aux Délices d'Élise", contact: "don ponctuel", pack: "Don 75 €", pack_chip: "outline", montant: 75, debut: "14 nov 2025", echeance: "—", jours_restants: null, statut: "ok", statut_label: "payé" },
    ],
  },
  {
    id: "2",
    sigle: "VE",
    nom: "VTT Évasion",
    president: "C. Roussel",
    discipline: "Cyclisme",
    licencies: 86,
    subventions: 14000,
    sponsoring: 4200,
    ratio: 0.30,
    dynamisme: "+12 %",
    statut: "actif",
    dynamisme_chip: "ok",
    interet_general: false,
    description: "12 sorties par an, écoles primaires incluses, parcours balisés.",
    equipes: 2,
    encadrants: 6,
    fonde: "2008",
    packs: [],
    sponsors: [],
  },
  {
    id: "3",
    sigle: "TP",
    nom: "Tennis Club du Parc",
    president: "M. Lévy",
    discipline: "Tennis",
    licencies: 142,
    subventions: 18000,
    sponsoring: 2760,
    ratio: 0.15,
    dynamisme: "stable",
    statut: "actif",
    dynamisme_chip: "warn",
    interet_general: false,
    description: "Tournoi régional annuel, 6 courts en terre battue, école de tennis.",
    equipes: 3,
    encadrants: 8,
    fonde: "1985",
    packs: [],
    sponsors: [],
  },
  {
    id: "4",
    sigle: "JA",
    nom: "Judo Akiyama",
    president: "S. Nakamura",
    discipline: "Judo",
    licencies: 94,
    subventions: 11000,
    sponsoring: 980,
    ratio: 0.09,
    dynamisme: "à surveiller",
    statut: "actif",
    dynamisme_chip: "warn",
    interet_general: false,
    description: "Dojo familial, 60 % d'enfants, ceintures noires bénévoles.",
    equipes: 2,
    encadrants: 5,
    fonde: "1999",
    packs: [],
    sponsors: [],
  },
  {
    id: "5",
    sigle: "BV",
    nom: "Boxing Villeneuve",
    president: "K. Diakité",
    discipline: "Boxe",
    licencies: 61,
    subventions: 8000,
    sponsoring: 250,
    ratio: 0.03,
    dynamisme: "à relancer",
    statut: "actif",
    dynamisme_chip: "bad",
    interet_general: false,
    description: "Championne France junior 2024. Recherche partenaires pour équipements.",
    equipes: 1,
    encadrants: 3,
    fonde: "2015",
    packs: [],
    sponsors: [],
  },
  {
    id: "6",
    sigle: "HA",
    nom: "Hand'Avenir",
    president: "A. Bouvier",
    discipline: "Handisport",
    licencies: 38,
    subventions: 4500,
    sponsoring: 0,
    ratio: 0.00,
    dynamisme: "aucun engagement",
    statut: "actif",
    dynamisme_chip: "bad",
    interet_general: false,
    description: "Club récemment fondé, ouvert à tous, basket fauteuil et tennis de table.",
    equipes: 1,
    encadrants: 4,
    fonde: "2023",
    packs: [],
    sponsors: [],
  },
  {
    id: "7",
    sigle: "AL",
    nom: "Aviron du Lac",
    president: "—",
    discipline: "Aviron",
    licencies: 0,
    subventions: 0,
    sponsoring: 0,
    ratio: 0,
    dynamisme: "non inscrit",
    statut: "invite",
    dynamisme_chip: "gray",
    interet_general: false,
    description: "",
    equipes: 0,
    encadrants: 0,
    fonde: "—",
    packs: [],
    sponsors: [],
  },
];

export const subventions_recentes = [
  { sigle: "FC", nom: "FC Villeneuve", source: "Municipale", montant: 20000, date: "15/10" },
  { sigle: "FC", nom: "FC Villeneuve", source: "CD 47", montant: 7000, date: "22/10" },
  { sigle: "TP", nom: "Tennis Parc", source: "Municipale", montant: 14000, date: "15/10" },
  { sigle: "BV", nom: "Boxing", source: "Municipale", montant: 5000, date: "15/10" },
  { sigle: "BV", nom: "Boxing", source: "ANS", montant: 3000, date: "14/11" },
  { sigle: "HA", nom: "Hand'Avenir", source: "Région", montant: 4500, date: "08/12" },
];

export const disciplines = ["Football", "Cyclisme", "Tennis", "Judo", "Boxe", "Handisport", "Aviron", "Natation"];

export const chart_months = ["sept", "oct", "nov", "déc", "janv", "févr", "mars", "avr", "mai", "juin"];
